Repository d2iq/ui-kit, pull requests merged in 2022-10, with the labels that each got.

#780 refactor: infobox component
  packages/infobox/components/InfoBox.tsx
  packages/infobox/tests/__snapshots__/InfoBox.test.tsx.snap
Labels: ready to review, hacktoberfest

#778 ci: update code checks and formatting
  .github/workflows/ci.yml
Labels: ready to review

#789 Refactor ToggleBoxGroup Component
  packages/toggleBox/components/ToggleBoxGroup.tsx
  packages/toggleBox/stories/helpers/ToggleBoxGroupStoryHelper.tsx
Labels: ready to review, hacktoberfest-accepted

#795 refactor: refactor Textarea into a functional component
  packages/textarea/components/Textarea.tsx
Labels: ready to review, hacktoberfest-accepted

#791 refactor: convert FormFieldWrapper to FC
  packages/radioInput/__snapshots__/radioInput.test.tsx.snap
  packages/selectInput/tests/__snapshots__/SelectInput.test.tsx.snap
  packages/shared/components/FormFieldWrapper.tsx
  packages/textInput/tests/__snapshots__/TextInput.test.tsx.snap
  packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
  packages/textInput/tests/__snapshots__/TextInputWithButtons.test.tsx.snap
  packages/textInput/tests/__snapshots__/TextInputWithIcon.test.tsx.snap
  packages/textarea/tests/__snapshots__/Textarea.test.tsx.snap
  packages/toggleInput/tests/__snapshots__/ToggleInput.test.tsx.snap
  packages/toggleInputList/tests/__snapshots__/ToggleInputList.test.tsx.snap
Labels: ready to review, hacktoberfest-accepted

#794 refactor: update tabs docs and tabitem to fc
  packages/tabs/README.md
  packages/tabs/components/TabItem.tsx
Labels: ready to review

#804 refactor: turn ToggleWrapper into a function component
  packages/toggleBox/components/ToggleBox.tsx
  packages/toggleWrapper/components/ToggleWrapper.tsx
  packages/toggleWrapper/tests/__snapshots__/ToggleWrapper.test.tsx.snap
Labels: ready to review, hacktoberfest-accepted

#798 refactor: DropdownContents Component to Function Component
  package-lock.json
  package.json
  packages/dropdownMenu/tests/__snapshots__/DropdownMenu.test.tsx.snap
  packages/dropdownable/components/DropdownContents.tsx
  packages/dropdownable/stories/helpers/DropdownStory.tsx
  packages/dropdownable/stories/helpers/DropdownStoryFit.tsx
  packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
  packages/popover/tests/__snapshots__/Popover.test.tsx.snap
  packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap
Labels: ready for review, hacktoberfest-accepted

#806 refactor: update Typeahead component tests from enzyme to react-testi…
  packages/typeahead/tests/Typeahead.test.tsx
Labels: ready for review, hacktoberfest-accepted

#808 Refactor/clickable to fc
  packages/clickable/components/clickable.tsx
  packages/clicktocopybutton/tests/__snapshots__/ClickToCopyButton.test.tsx.snap
  packages/codesnippet/tests/__snapshots__/CodeSnippet.test.tsx.snap
  packages/infobox/tests/__snapshots__/InfoBox.test.tsx.snap
  packages/modal/tests/__snapshots__/Modal.test.tsx.snap
  packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
Labels: ready for review, hacktoberfest-accepted

#809 docs: story for infobox component
  packages/infobox/stories/InfoBox.stories.tsx
Labels: ready for review, hacktoberfest-accepted

#816 feat: add message control to infobox stories
  packages/infobox/stories/InfoBox.stories.tsx
  packages/infobox/stories/InfoBoxBanner.stories.tsx
Labels: ready for review

#821 refactor: update Popover component tests from enzyme to react-testing…
  packages/popover/tests/Popover.test.tsx
  packages/popover/tests/__snapshots__/Popover.test.tsx.snap
Labels: ready for review, hacktoberfest-accepted

#822 refactor: convert ConfigurationMap tests from enzyme to RTL
  packages/configurationmap/tests/ConfigurationMap.test.tsx
  packages/configurationmap/tests/__snapshots__/ConfigurationMap.test.tsx.snap
Labels: ready for review

#815 refactor: more refactoring away enzyme to rtl
  packages/button/tests/ButtonBase.test.tsx
  packages/clicktocopybutton/tests/ClickToCopyButton.test.tsx
  packages/clicktocopybutton/tests/__snapshots__/ClickToCopyButton.test.tsx.snap
  packages/formStructure/tests/__snapshots__/fieldGroup.test.tsx.snap
  packages/formStructure/tests/__snapshots__/formStructure.test.tsx.snap
  packages/formStructure/tests/fieldGroup.test.tsx
  packages/formStructure/tests/formStructure.test.tsx
  packages/formStructure/tests/formSubSection.test.tsx
  packages/fullscreenView/tests/__snapshots__/fullscreenView.test.tsx.snap
  packages/fullscreenView/tests/fullscreenView.test.tsx
  packages/infobox/tests/InfoBox.test.tsx
  packages/infobox/tests/__snapshots__/InfoBox.test.tsx.snap
  packages/radioInput/__snapshots__/radioInput.test.tsx.snap
  packages/radioInput/radioInput.test.tsx
  packages/styleUtils/layout/container/tests/Container.test.tsx
  packages/styleUtils/layout/container/tests/__snapshots__/Container.test.tsx.snap
  packages/styleUtils/layout/gridList/tests/GridList.test.tsx
  packages/styleUtils/layout/gridList/tests/__snapshots__/GridList.test.tsx.snap
  packages/styleUtils/layout/stack/tests/__snapshots__/stack.test.tsx.snap
  packages/styleUtils/layout/stack/tests/stack.test.tsx
  packages/styleUtils/typography/tests/__snapshots__/typographyComponents.test.tsx.snap
  packages/styleUtils/typography/tests/typographyComponents.test.tsx
  packages/tabs/tests/Tabs.test.tsx
  packages/tabs/tests/__snapshots__/Tabs.test.tsx.snap
  packages/toggleBox/tests/ToggleBox.test.tsx
  packages/toggleInput/tests/ToggleInput.test.tsx
  packages/toggleInput/tests/__snapshots__/ToggleInput.test.tsx.snap
  packages/toggleWrapper/tests/ToggleWrapper.test.tsx
  packages/toggleWrapper/tests/__snapshots__/ToggleWrapper.test.tsx.snap
Labels: ready for review, hacktoberfest-accepted

#824 feat: optional max-width for FullscreenView header
  packages/fullscreenView/components/FullscreenView.tsx
  packages/fullscreenView/stories/fullscreenView.stories.tsx
  packages/modal/tests/__snapshots__/Modal.test.tsx.snap
Labels: ready for review

#827 refactor: move wrapping react.memo to export
  packages/breadcrumb/components/Breadcrumb.tsx
  packages/card/components/ButtonCard.tsx
  packages/card/components/Card.tsx
  packages/card/components/LinkCard.tsx
  packages/codesnippet/tests/__snapshots__/CodeSnippet.test.tsx.snap
  packages/configurationmap/components/HashMap.tsx
  packages/donutChart/components/DonutChart.tsx
  packages/formStructure/components/FieldList.tsx
  packages/formStructure/stories/helpers/FieldListStoryHelper.tsx
  packages/modal/components/FullscreenModal.tsx
  packages/modal/tests/__snapshots__/Modal.test.tsx.snap
  packages/pageheader/components/PageHeader.tsx
  packages/pagination/__snapshots__/pagination.test.tsx.snap
  packages/segmentedControl/components/SegmentedControlButton.tsx
  packages/segmentedControl/stories/helpers/SegmentedControlStoryHelper.tsx
  packages/segmentedControl/tests/__snapshots__/SegmentedControl.test.tsx.snap
  packages/selectInput/components/SelectInput.tsx
  packages/selectInput/tests/__snapshots__/SelectInput.test.tsx.snap
  packages/tablev2/__snapshots__/tablev2.test.tsx.snap
  packages/textInput/stories/helpers/TextInputWithBadgesStoryHelper.tsx
  packages/tooltip/components/TooltipContent.tsx
  packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap
  packages/typeahead/components/Typeahead.tsx
  packages/typeahead/stories/helpers/FilteredListTypeahead.tsx
Labels: ready for review

#801 Refactor TextInput related components from classes to functional components
  packages/textInput/components/TextInput.tsx
  packages/textInput/components/TextInputWithBadges.tsx
  packages/textInput/components/TextInputWithButtons.tsx
  packages/textInput/components/TextInputWithIcon.tsx
  packages/textInput/components/utils.tsx
Labels: ready for review, hacktoberfest-accepted

#826 refactor: togglecontent component, story, and test
  packages/toggleContent/components/ToggleContent.tsx
  packages/toggleContent/components/toggleContent.tsx
  packages/toggleContent/index.ts
  packages/toggleContent/stories/ToggleContent.stories.tsx
  packages/toggleContent/stories/toggleContent.stories.tsx
  packages/toggleContent/tests/ToggleContent.test.tsx
  packages/toggleContent/tests/__snapshots__/ToggleContent.test.tsx.snap
  packages/toggleContent/tests/toggleContent.test.tsx
Labels: ready for review

#829 refactor: converts ToggleInputList class component into a function co…
  packages/toggleInputList/components/ToggleInputList.tsx
  packages/toggleInputList/tests/__snapshots__/ToggleInputList.test.tsx.snap
Labels: ready for review, hacktoberfest-accepted

#837 refactor: remove statelesscomponent use
  packages/popover/components/Popover.tsx
  packages/progressbar/components/ProgressBar.tsx
  packages/promo/components/PromoInline.tsx
  packages/styleUtils/layout/stack/components/Stack.tsx
  packages/styleUtils/typography/components/TextBlock.tsx
  packages/tablev2/DropdownMenuCell.tsx
  packages/tablev2/TooltipHeaderCell.tsx
Labels: ready for review

#834 refactor: togglebox story
  packages/toggleBox/stories/ToggleBox.stories.tsx
  packages/toggleBox/stories/helpers/ToggleBoxStoryHelper.tsx
Labels: ready for review

#831 refactor: DialogModal to Function Component
  packages/modal/components/DialogModal.tsx
  packages/modal/components/DialogModalWithFooter.tsx
  packages/modal/components/ModalBase.tsx
  packages/modal/components/helpers/ModalExample.tsx
  packages/modal/tests/__snapshots__/Modal.test.tsx.snap
Labels: ready for review, hacktoberfest-accepted

#836 chore: dependency maintenance
  package-lock.json
  package.json
Labels: ready for review

#838 refactor: buttonbase from class to fc
  packages/button/components/ButtonBase.tsx
  packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
  packages/modal/tests/__snapshots__/Modal.test.tsx.snap
Labels: ready for review

#839 refactor: migrate Overlay from class to function component
  packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
  packages/modal/tests/__snapshots__/Modal.test.tsx.snap
  packages/shared/components/Overlay.tsx
  packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap
Labels: ready for review, hacktoberfest

#851 refactor: selectInput tests
  packages/selectInput/tests/SelectInput.test.tsx
  packages/selectInput/tests/__snapshots__/SelectInput.test.tsx.snap
Labels: ready for review, hacktoberfest-accepted

#849 Refactor test cases of dropdownable and dropdown menu item
  packages/dropdownMenu/tests/DropdownMenuItem.test.tsx
  packages/dropdownMenu/tests/__snapshots__/DropdownMenuItem.test.tsx.snap
  packages/dropdownable/tests/Dropdownable.test.tsx
  packages/dropdownable/tests/__snapshots__/Dropdownable.test.tsx.snap
Labels: ready for review, hacktoberfest-accepted

#847 refactor: convert enzym tests to react-testing-library-tests
  packages/pagination/Pagination.tsx
  packages/pagination/__snapshots__/pagination.test.tsx.snap
  packages/pagination/pagination.test.tsx
  packages/promo/__snapshots__/promos.test.tsx.snap
  packages/promo/components/PromoContent.tsx
  packages/promo/promos.test.tsx
  packages/segmentedControl/tests/SegmentedControl.test.tsx
  packages/segmentedControl/tests/__snapshots__/SegmentedControl.test.tsx.snap
Labels: ready for review, hacktoberfest-accepted

#852 refactor: tooltip tests
  packages/tooltip/tests/Tooltip.test.tsx
  packages/tooltip/tests/__snapshots__/Tooltip.test.tsx.snap
Labels: ready for review, hacktoberfest-accepted

#846 refactor: migrate table component tests from enzyme to rtl
  packages/tablev2/Table.tsx
  packages/tablev2/__snapshots__/tablev2.test.tsx.snap
  packages/tablev2/tablev2.test.tsx
Labels: ready for review, hacktoberfest-accepted

#857 refactor: textInput tests
  packages/selectInput/tests/__snapshots__/SelectInput.test.tsx.snap
  packages/textInput/tests/TextInput.test.tsx
  packages/textInput/tests/TextInputWithBadges.test.tsx
  packages/textInput/tests/TextInputWithButtons.test.tsx
  packages/textInput/tests/__snapshots__/TextInput.test.tsx.snap
  packages/textInput/tests/__snapshots__/TextInputWithBadges.test.tsx.snap
  packages/textInput/tests/__snapshots__/TextInputWithButtons.test.tsx.snap
  packages/textInput/tests/__snapshots__/TextInputWithIcon.test.tsx.snap
  packages/textarea/tests/Textarea.test.tsx
  packages/textarea/tests/__snapshots__/Textarea.test.tsx.snap
  packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap
  packages/utilities/label.tsx
Labels: ready for review, hacktoberfest-accepted

#859 refactor: toggleInputList tests
  packages/toggleBox/tests/ToggleBoxGroup.test.tsx
  packages/toggleBox/tests/__snapshots__/ToggleBoxGroup.test.tsx.snap
  packages/toggleInputList/components/ToggleInputList.tsx
  packages/toggleInputList/tests/ToggleInputList.test.tsx
  packages/toggleInputList/tests/__snapshots__/ToggleInputList.test.tsx.snap
Labels: ready for review, hacktoberfest-accepted

#865 fix: console error for togglewrapper
  packages/toggleWrapper/components/ToggleWrapper.tsx
Labels: ready for review

#868 refactor: tests to rtl
  packages/modal/tests/Modal.test.tsx
  packages/modal/tests/__snapshots__/Modal.test.tsx.snap
  packages/textInput/tests/TextInputWithIcon.test.tsx
  packages/textInput/tests/__snapshots__/TextInputWithIcon.test.tsx.snap
Labels: ready for review
