Repository d2iq/ui-kit, pull requests merged in 2022-11, with the labels that each got.

#863 Refactor testcases expandable
  packages/expandable/tests/Expandable.test.tsx
  packages/expandable/tests/__snapshots__/Expandable.test.tsx.snap
Labels: ready for review, hacktoberfest-accepted

#867 test: toaster tests with RTL
  packages/toaster/components/Toaster.tsx
  packages/toaster/stories/Toaster.stories.tsx
  packages/toaster/tests/Toaster.test.tsx
Labels: hold merge

#873 PageHeader new custom properties
  packages/pageheader/components/PageHeader.tsx
  packages/pageheader/stories/PageHeader.stories.tsx
Labels: ready for review

#871 chore: node suggested engines
  package-lock.json
  package.json
Labels: ready for review

#875 feat: react 18
  package-lock.json
  package.json
  packages/accordion/components/AccordionItemTitleInteractive.tsx
  packages/badge/tests/__snapshots__/badge.test.tsx.snap
  packages/badge/tests/badge.test.tsx
  packages/card/tests/ButtonCard.test.tsx
  packages/configurationmap/tests/HashMap.test.tsx
  packages/configurationmap/tests/__snapshots__/HashMap.test.tsx.snap
  packages/donutChart/tests/DonutChart.test.tsx
  packages/donutChart/tests/__snapshots__/DonutChart.test.tsx.snap
  packages/dropdownMenu/components/DropdownMenu.tsx
  packages/expandable/tests/Expandable.test.tsx
  packages/formStructure/components/FieldListColumn.tsx
  packages/popover/tests/Popover.test.tsx
  packages/selectInput/tests/SelectInput.test.tsx
  packages/tablev2/tablev2.test.tsx
  packages/tabs/components/Tabs.tsx
  packages/tabs/tests/__snapshots__/Tabs.test.tsx.snap
  packages/toggleBox/components/ToggleBoxGroup.tsx
  packages/toggleContent/tests/ToggleContent.test.tsx
  packages/toggleWrapper/components/ToggleWrapper.tsx
  packages/typeahead/tests/Typeahead.test.tsx
  packages/typeahead/tests/__snapshots__/Typeahead.test.tsx.snap
Labels: ready for review

#876 Dependency Updates and MDX2 support
  .storybook/docs/stories/Colors.stories.mdx
  .storybook/docs/stories/Welcome.stories.mdx
  .storybook/main.js
  package-lock.json
  package.json
Labels: ready for review

#877 docs: steps and check for downstream testing
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: ready for review

#878 feat: create environment for every PR using Uffizzi
  .github/workflows/uffizzi-build.yml
  .github/workflows/uffizzi-preview.yml
  docker-compose.uffizzi.yml
Labels: ready for review

#882 fix: duplicate key in tabs component
  packages/tabs/components/Tabs.tsx
  packages/tabs/stories/Tabs.stories.tsx
Labels: ready for review

#885 fix: use react-id-generator
  packages/tabs/components/Tabs.tsx
Labels: ready for review

#886 Fix Tab Component again
  packages/tabs/components/Tabs.tsx
  packages/tabs/stories/Tabs.stories.tsx
Labels: ready for review
